// Generated by LiveScript 1.2.0
(function(){
  var ability, factories, Ability, createUser;
  ability = require('../../index');
  factories = require('../factories');
  Ability = ability.Ability;
  createUser = factories.createUser;
  ability = function(user){
    return new Ability(user);
  };
  module.exports = {
    kris: ability(createUser.kris()),
    guest: ability(createUser.guest()),
    admin: ability(createUser.admin())
  };
}).call(this);
