// Generated by LiveScript 1.2.0
(function(){
  var ability, factories, CachedAbility, createUser;
  ability = require('../../index');
  factories = require('../factories');
  CachedAbility = ability.CachedAbility;
  createUser = factories.createUser;
  ability = function(user){
    return new CachedAbility(user);
  };
  module.exports = {
    kris: ability(createUser.kris()),
    guest: ability(createUser.guest()),
    admin: ability(createUser.admin())
  };
}).call(this);
